sudo:          required
dist:          trusty
language:      node_js
node_js:
  - "node"
install:       
  - npm install
  - npm install -g protractor
  - webdriver-manager update
script:
  - webdriver-manager start
  - protractor Tests/UI Tests/conf.js
cache:
  directories:
    - node_modules
