sudo:          required
dist:          trusty
language:      node_js
node_js:
  - "node"
install:       
  - npm install
  - npm install -g protractor
  - webdriver-manager update
before_script:
  - webdriver-manager start
script:
  - protractor conf.js
cache:
  directories:
    - node_modules
